export { default as Navbar } from '@/components/Navbar/Navbar'
export { default as Sidebar } from '@/components/Sidebar/Sidebar'
export { default as Categories } from '@/components/Categories/CategoryContainer'
export { default as Videos } from '@/components/Videos/VideoContainer'
export { default as RelatedVideos } from '@/components/Videos/RelatedVideos'
export { default as VideoDetail } from '@/components/Videos/VideoDetail'
export { default as Comments } from '@/components/Videos/Comments'

export { default as HomeContent } from '@/components/Contents/HomeContent'
export { default as WatchContent } from '@/components/Contents/WatchContent'